[package]
name = "gitpatcher-bin"
version = "0.1.0"
authors = ["Techcable <Techcable@techcable.net>"]
edition = "2018"

[[bin]]
name = "gitpatcher"
path = "src/main.rs"

[dependencies]
gitpatcher = { path = ".." }
slog = "2.5.2"
structopt = "0.3.14"
structopt-derive = "0.4.7"


[dependencies.git2]
version = "^0.13.6"
# We don't need https
default-features = false
