[package]
name = "gitpatcher-bin"
version = "0.1.1"
authors = ["Techcable <Techcable@techcable.net>"]
edition = "2018"
description = """A command line app for using gitpatcher"""
license = "MIT"
repository = "https://github.com/Techcable/gitpatcher"

[[bin]]
name = "gitpatcher"
path = "src/main.rs"

[dependencies]
gitpatcher = { version = "^0.1.0", path = ".." }
slog.workspace = true
clap = { version = "4.3", default-features = false, features = ["std", "suggestions", "derive"]}
git2.workspace = true
