[package]
name = "gitpatcher-bin"
description = """A command line app for using gitpatcher"""
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true
# Used to compute build version
build = "build.rs"

[[bin]]
name = "gitpatcher"
path = "src/main.rs"

[features]
# Enable vendored copy of libgit2
vendored-libgit2 = ["git2/vendored-libgit2"]
# Use static linking for all dependencies (including libgit2)
static = ["libz-sys/static", "vendored-libgit2"]

[dependencies]
gitpatcher = { version = "0.2.0", path = ".." }
anyhow = "1"
slog.workspace = true
camino.workspace = true
clap = { version = "4.3", features = ["derive"] }
git2.workspace = true
# Confiured to maybe be static
libz-sys = { version = "1" }
# Log backend
slog-term = "2.9"

[build-dependencies]
# Already using libgit2 for engine, might as well use for versions
#
# TODO: Switch back to git2.
# Right now can't use it because of version conflict
vergen = { version = "8.2", features = ["git", "gitcl"] }
