[package]
name = "gitpatcher-bin"
description = """A command line app for using gitpatcher"""
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "gitpatcher"
path = "src/main.rs"

[dependencies]
gitpatcher = { version = "0.1.0", path = ".." }
slog.workspace = true
clap = { version = "4.3", default-features = false, features = ["std", "suggestions", "derive"]}
git2.workspace = true
