[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.3.0-alpha.0" # pre-alpha
edition = "2024"
authors = ["Techcable <Techcable@techcable.net>"]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Techcable/gitpatcher"
# 1.85 - Rust 2024
rust-version = "1.85"

[workspace.dependencies]
slog = "2.7"
# UTF8 paths
camino = "1.1.6"

[workspace.dependencies.gitpatcher]
version = "0.3.0-alpha.0"
path = "crates/gitpatcher"

[workspace.dependencies.git2]
version = "0.21"
# We don't need https
default-features = false

[profile.release]
# Counterintuitively, this produces smaller binaries
opt-level = 3
# Use (thin) link time optimization to enable more optimization opportunities
# Note: Unlike regular LTO, thin LTO actually doesn't ruin compile times
lto = "thin"
# Panics are only used for internal errors.
# If we want to recover, we use a Result.
# As far as we're concerned, a panic is fatal and should exit the command line app
# This choice does not affect the quality of panic messages or backtraces in any way.
panic = "abort"
# Adding this information means the unwinder can include line numbers for all stack
# frames instead of just the one function that called the `panic!()`.
# Optimizations may interfere with the unwinder's ability to recover these line numbers.
# However, having this information sometimes is better than never having it at all.
debug = "line-tables-only"

[workspace.metadata.cargo-reedme]
note = "Do not edit - automatically generated by cargo-reedme"
