[package]
name = "gitpatcher"
version = "0.1.0"
authors = ["Techcable <Techcable@techcable.net>"]
edition = "2018"

[dependencies]
slog = "2.5.2"
regex = "1.3.7"
lazy_static = "1.4.0"
itertools = "0.9.0"
chrono = "0.4.11"

[dependencies.git2]
# TODO: Use relased crates.io version
git = "https://github.com/rust-lang/git2-rs"
rev = "d05202f3e842bb9cc08ed734d6537"
# We don't need https
default-features = false

[workspace]
members = ["bin"]