[package]
name = "gitpatcher"
version = "0.1.0"
authors = ["Techcable <Techcable@techcable.net>"]
edition = "2018"

[[bin]]
name = "regenerate-patches"
path = "src/bin/regenerate_patches.rs"

[dependencies]
slog = "2.5.2"
regex = "1.3.7"
lazy_static = "1.4.0"
itertools = "0.9.0"

[dependencies.git2]
git = "https://github.com/Techcable/git2-rs"
branch = "feature/diff-format-email"
# We don't need https
default-features = false

