[package]
name = "gitpatcher"
version = "0.1.0"
authors = ["Techcable <Techcable@techcable.net>"]
edition = "2018"

[dependencies]
slog = "2.5.2"
lazy_static = "1.4.0"
itertools = "0.9.0"
chrono = "0.4.11"

[dependencies.regex]
version = "^1"
# Reduce size (at the expense of performance)
# Right now we disable 'perf' and 'unicode'
default-features = false
features = ["std"]

[dependencies.git2]
version = "^0.13.6"
# We don't need https
default-features = false

[workspace]
members = ["bin"]

[profile.release]
# Optimize for size, not speed (note this is still way faster than -O0)
opt-level = 's'
# Use (thin) link time optimization to enable more optimization opportunities
# Note: Unlike regular LTO, thin LTO actually doesn't ruin compile times
lto = "thin"
# Panics are only used for internal errors.
# If we want to recover, we use a Result.
# As far as we're concerned a panic is fatal,
# and should exit the command line app.
panic = "abort"