[package]
name = "gitpatcher"
description = "A library that uses git to maintain a set of patches around a submodule"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bstr = "1.5"
thiserror = "2"
nom = "7.1.3"
arrayvec = "0.7.2"
time = { version = "0.3", features = ["macros", "parsing"] }
slog.workspace = true
git2.workspace = true
camino.workspace = true
# Used to apply patches
diffy = "0.5"

[features]
# Add backtraces to error types
#
# Currently requires nightly feature `error_generic_member_access`.
# On stable rust, this feature is automatically disabled.
backtrace = []

[build-dependencies]
rustversion-detect = "0.2"

[dev-dependencies]
anyhow = "1"
testdir = "0.10"

[package.metadata.cargo-shear]
ignored-paths = [
    # not actually project code
    "tests/data/**",
]
