[package]
name = "gitpatcher-bin"
description = "A command line app for using gitpatcher"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false # v0.3 is still pre-alpha
# Used to compute build version
build = "build.rs"

[[bin]]
name = "gitpatcher"
path = "src/main.rs"

[features]
default = []
# Use static linking for all C dependencies.
# Right now this does nothing.
static = []

[dependencies]
gitpatcher.workspace = true
anyhow = "1"
camino.workspace = true
clap = { version = "4.3", features = ["derive"] }
# Logging
slog = { workspace = true, features = ["max_level_trace"] }
slog-scope.workspace = true
slog-term = { version = "2.9", features = ["nested-values"] }

[build-dependencies]
# Avoid using libgit2 at build-time, as it causes issues during cross-compilation.
# Counterintuitively, it is more portable to assume the presence of a git CLI than a C library.
vergen-gitcl = "10"

[lints]
workspace = true

[package.metadata.cargo-shear]
ignored = []
