# Unified workflow for all lints & tests.
#
# Based on the biasedrc CI config
# Indirectly based on the slog CI config.
# All merged into one file so we can use `allgood` workaround for Gihtub Actions.
on: [push, pull_request]
name: CI

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1
  # has a history of occasional bugs (especially on old versions)
  #
  # the ci is free so we might as well use it ;)
  CARGO_INCREMENTAL: 0


jobs:
  test:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Even if one job fails we still want to see the other ones
      matrix:
        rust:
          # Minimum Supported Rust Version
          #
          # This is hardcoded and needs to be in sync with Cargo.toml and the README
          # - <not currently specified>

          # Intermediate Releases (between MSRV and latest stable)
          # Be careful not to add these needlessly; they hold up CI

          # The most recent version of stable rust (automatically updated)
          - stable
          - nightly
        # NOTE: Features to test must be specified manually. They are applied to all versions separately.
        features:
          - ""
          - "gitpatcher-bin/vendored-libgit2"
          - "gitpatcher-bin/static"
        include:
          # all nightly features together
          - rust: nightly
            features: "backtrace"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - uses: Swatinem/rust-cache@v2
      - name: Pin MSRV-compatible versions
        if: ${{ contains(matrix.rust, '1.') }}  # ignored for non-pinned versions
        env:
          # this option is where the magic happens
          CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS: fallback
        run: |
          rm -f Cargo.lock
          cargo +stable update
      - name: Test
        # NOTE: Running --all-targets actually excludes doc tests. See rust-lang/cargo#6669
        # The `--all` flag is equivalent to `--workspace`
        run: |
          cargo nextest run --workspace --verbose --no-default-features --features "${{ matrix.features }}"
      # nextest doesn't support doctests (https://github.com/nextest-rs/nextest/issues/16)
      - name: Doctests
        run: |
          cargo test --doc --workspace --verbose --no-default-features --features "${{ matrix.features }}"

  clippy:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          # in hardcoded versions, warnings will fail the build
          - 1.96
          # in auto-updated versions, warnings will not fail the build
          - stable
          - nightly
        features:
          - ""
        include:
          # all nightly features together
          - rust: nightly
            features: "backtrace"

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Clippy
        # The `--all` flag is equivalent to `--workspace`
        run: |
          cargo clippy --workspace --all-targets --verbose --no-default-features --features "${{ matrix.features }}" -- -D warnings
        # When using hardcoded/pinned versions, warnings are forbidden.
        #
        # On automatically updated versions of rust (both stable & nightly) we allow clippy to fail.
        # This is because automatic updates can introduce new lints or change existing lints.
        continue-on-error: ${{ !contains(matrix.rust, '1.') }}

  docs:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}

    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"
    strategy:
      fail-fast: false
      matrix:
        rust:
          - nightly
          - stable
        features:
          - ""
        include:
          # all nightly features together
          - rust: nightly
            features: "backtrace"

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
      - name: Docs
        # NOTE: Passing --document-private-items is needed to check for doc errors in private items
        run: |
          cargo doc --document-private-items --no-deps --workspace --verbose --no-default-features --features "${{ matrix.features }}"
  cargo-reedme:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly  # cargo-reedme requires nightly
        with:
          components: rust-src
      - uses: taiki-e/cache-cargo-install-action@v3  # not supported by regular install action
        with:
          tool: cargo-reedme
      - uses: Swatinem/rust-cache@v2
        with:
          # cached separately
          cache-bin: false
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v6
      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v8.2.0
      - name: Install pyinvoke
        id: install-pyinvoke
        run: |
          uv tool install invoke
      - name: Run cargo-reedme
        # We only want to sync the readmes of a subset of packages for reasons explained in tasks.py.
        # Delegate to pyinvoke in order to keep the list of packages in one central place.
        run: |
          invoke cargo-reedme --check
  typos:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run typos (pinned version)
        uses: crate-ci/typos@v1.47.2
  rustfmt:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        # need nightly for unstable formatting features
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - shell: bash
        # While `--all` is normally an alias for `--workspace`, `cargo fmt` doesn't accept the latter
        run: |
          cargo fmt --all -- --check
  tombi:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: tombi-toml/setup-tombi@v1.2.3
      - run: |
          tombi format --check
  cargo-sort:
    if: false # disabled
    # Only run on PRs if the source branch is on someone else's repo
    # if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-sort
      - run: |
          cargo sort --grouped --workspace --check .
  pyfmt:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"
      - uses: astral-sh/ruff-action@v3
        name: isort with ruff
        with:
          args: "check --select=I --diff"
  # Workaround for Github status checks to require that all tests pass
  # Discussion: https://github.com/orgs/community/discussions/26733
  # App: https://github.com/marketplace/actions/alls-green
  allgood:
    if: always()
    needs: [test,clippy,docs,cargo-reedme,typos,rustfmt,tombi,pyfmt]
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          # allowed-failures: docs, linters
          # allowed-skips: non-voting-flaky-job
          jobs: ${{ toJSON(needs) }}
